language: php

php:
- 7.0
- 7.1
- 7.2
- hhvm

services:
  - docker

env:
- TESTER_PHP_BIN="php-cgi"
- TESTER_PHP_BIN="hhvm"

matrix:
  allow_failures:
  - php: hhvm

  exclude:
  - php: 7.0
    env: TESTER_PHP_BIN="hhvm"

  - php: 7.1
    env: TESTER_PHP_BIN="hhvm"

  - php: 7.2
    env: TESTER_PHP_BIN="hhvm"

  - php: hhvm
    env: TESTER_PHP_BIN="php-cgi"

before_install:
- composer self-update

install:
- composer update --no-interaction --prefer-source

script:
- ./kickstart.sh test

